!!python/object:argparse.Namespace
batch_size: 100
dataset_state_dict_filename: dataset_state_dict.pkl
dist_backend: nccl
dist_url: tcp://localhost:13456
distributed: 0
embedding_size: 24
epochs: 1000
fc_activation: ReLU
fc_batch_norm: 0
fc_dropout: 0.0
fc_hidden_size:
- 64
- 32
fc_num_layers: 2
feature_size:
  atom: 22
  bond: 11
  global: 3
gated_activation: ReLU
gated_batch_norm: 1
gated_dropout: 0.0
gated_graph_norm: 0
gated_hidden_size:
- 64
- 64
- 64
gated_num_fc_layers: 2
gated_num_layers: 3
gated_residual: 1
gpu: null
lr: 0.001
molecule_attributes_file: molecule_attributes.yaml
molecule_file: molecules.sdf
num_gpu: null
num_lstm_iters: 6
num_lstm_layers: 3
output_file: results.pkl
reaction_file: reactions.yaml
restore: 0
set2set_ntypes_direct:
- global
start_epoch: 0
weight_decay: 0.0
